apiVersion: v1
kind: Service
metadata:
  name: my-apache-service
spec:
  selector:
    app: simple-app
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    name: my-apache-service
