apiVersion: v1
kind: Service
metadata:
  name: snake-service
spec:
  selector:
    app: snake-games
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    name: snake-service
