apiVersion: apps/v1
kind: Deployment
metadata:
  name: snake-games
  labels:
    app: snake-games
spec:
  replicas: 1
  selector:
    matchLabels:
      app: snake-games
  template:
    metadata:
      labels:
        app: snake-games
    spec:
      containers:
        - name: snake-games
          image: islamifauzi/snake-games:latest
          ports:
            - containerPort: 80
